name: Build Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.5'

      - name: Install dependencies
        run: yarn install

      - name: Set up Keystore
        run: |
          mkdir -p ~/.android
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > ~/.android/my-release-key.jks
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Set up Gradle signing properties
        run: |
          echo "MY_KEYSTORE_PASSWORD=${{ secrets.MY_KEYSTORE_PASSWORD }}" >> android/gradle.properties
          echo "MY_KEY_ALIAS=${{ secrets.MY_KEY_ALIAS }}" >> android/gradle.properties
          echo "MY_KEY_PASSWORD=${{ secrets.MY_KEY_PASSWORD }}" >> android/gradle.properties
        env:
          MY_KEYSTORE_PASSWORD: ${{ secrets.MY_KEYSTORE_PASSWORD }}
          MY_KEY_ALIAS: ${{ secrets.MY_KEY_ALIAS }}
          MY_KEY_PASSWORD: ${{ secrets.MY_KEY_PASSWORD }}

      - name: Build Android
        run: |
          cd android
          ./gradlew clean assembleRelease  # This generates the APK

      # List contents of the build output directory for debugging
      - name: List output directory contents
        run: |
          ls -R android/app/build/outputs/

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
